version: '3.8'
services:
  web:
    build:
      context: .
      args:
        MYEMAIL: ${MYEMAIL}
        PASSWORD: ${PASSWORD}
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
      - MYEMAIL=${MYEMAIL}
      - PASSWORD=${PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=aditya
      - MYSQL_PASSWORD=Admin12345
      - MYSQL_DB=posts
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://aditya:Admin12345@mysql:3306/posts
    networks:
      - app-network
    command: ["/wait.sh", "mysql:3306", "--", "python", "main.py"]
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: posts
      MYSQL_USER: aditya
      MYSQL_PASSWORD: Admin12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
